home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.products_list, name='products'),
    path('<int:product_id>/', views.product_info, name='product_info'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<int:product_id>/', views.edit_product,
         name='edit_product'),
    path('delete_product/<int:product_id>/', views.delete_product,
         name='delete_product'),
]

wagging_tailor/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('shopping_bag/', include('shopping_bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('my_profile.urls')),
    path('queries/', include('queries.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "wagging_tailor.views.handler404"

checkout/models.py
"""
Checkout Views
"""
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField

from products.models import Product
from my_profile.models import UsersProfile


# Create your models here.
class Order(models.Model):
    """
    Order view displays the information required in the checkout
    which will also display in the order confirmation and history.
    """
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UsersProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    county = models.CharField(max_length=80, null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    shipping_cost = models.DecimalField(max_digits=6, decimal_places=2,
                                        null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)

    def _create_order_number(self):
        """
        Creates a unique order number at random for the user and site owner to
        track a purchase
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Updates the grand total of the shopping bag each time a line item is
        added, taking shipping costs into account.
        """
        self.order_total = (
            self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        )
        if self.order_total < settings.FREE_SHIPPING_THRESHOLD:
            self.shipping_cost = (
                self.order_total * settings.STANDARD_SHIPPING_PERCENTAGE / 100
            )
        else:
            self.shipping_cost = 0
        self.grand_total = self.order_total + self.shipping_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Overrides the initial save method to set the order number in case
        it has not already been set.
        """
        if not self.order_number:
            self.order_number = self._create_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    """
    This generates a unique id for each order placed.
    """
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False,
                                on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2,
                                         null=False, blank=False,
                                         editable=False)

    def save(self, *args, **kwargs):
        """
        Overrides the initial save method to set the lineitem_total in case
        and also update the order_total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order.order_number

products/models.py
"""
Products Models
"""
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    """
    Defines the Category Model used to filter products by category
    """
    class Meta:
        """
        This class changes the admin from the default display 'Categorys'
        to 'Categories
        """
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return str(self.name)

    def get_friendly_name(self):
        """
        Get's the friendly name
        """
        return self.friendly_name


class Product(models.Model):
    """
    Defines the Product Model used to show each product in the shop and in
    the product details pages.
    """
    name = models.CharField(max_length=254)
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    description = models.TextField()
    sizes_available = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=1, null=True,
                                 blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return str(self.name)


class Comment(models.Model):
    """
    Comment class
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='comments')
    author = models.ForeignKey(User, blank=False, null=False,
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    body = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    comment_image = models.ImageField(null=True, blank=True)

    class Meta:
        """
        Ordering our posts in created order,
        the lack of '-' means in ascending order.
        """
        ordering = ['-date_created']

    def __str__(self):
        """
        Returns a string showing the authors name
        and the content of the comment.
        """
        return f"Comment on {self.product.name} by {self.author}"

products/forms.py
"""
Product Forms
"""
from django import forms
from .models import Product, Category, Comment


class ProductForm(forms.ModelForm):
    """
    The Product form allows the user to add a product to the store.
    """
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-navy rounded-0'


class CommentForm(forms.ModelForm):
    """
    The Comment Form allows users to add comments to the site.
    """
    class Meta:
        model = Comment
        fields = ['title', 'body']

products/views.py
"""
Products Views
"""
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Product, Category
from .forms import ProductForm, CommentForm


# Create your views here.
def products_list(request):
    """
    The Products List view displays the list of products, as well as
    sorting and search queries
    """
    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sort_key = request.GET['sort']
            sort = sort_key
            if sort_key == 'name':
                sort_key = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sort_key == 'category':
                sort_key = 'category__name'

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sort_key = f'-{sort_key}'
            products = products.order_by(sort_key)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request,
                               "You didn't enter any search criteria!")
                return redirect(reverse('products'))
            queries = (
                Q(name__icontains=query) | Q(description__icontains=query)
            )
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }
    return render(request, 'products/products.html', context)


def product_info(request, product_id):
    """
    The Product Info view displays the information for individual products.
    """
    product = get_object_or_404(Product, pk=product_id)
    if request.user:
        if request.method == 'POST':
            form = CommentForm(request.POST)

            if form.is_valid():
                comment = form.save(commit=False)
                comment.author = request.user
                comment.product = product
                comment.save()

                return redirect(reverse('product_info', args=[product.id]))
        else:
            form = CommentForm()

    context = {
        'product': product,
        'form': form,
    }

    return render(request, 'products/product_info.html', context)


@login_required
def add_product(request):
    """
    Used to add a product to the store
    """
    if not request.user.is_superuser:
        messages.error(request, "Sorry, you don't have permission to do that.")
        return redirect(reverse('home'))

    if request.method == 'POST':
        product_form = ProductForm(request.POST, request.FILES)
        if product_form.is_valid():
            product = product_form.save()
            messages.success(request, 'You have successfully added a new \
                product')
            return redirect(reverse('product_info', args=[product.id]))
        else:
            messages.error(request,
                           ("I'm sorry, that product was not added. "
                            "Please check your form and try again."))
    else:
        product_form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'product_form': product_form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """
    Used to add a product in the store
    """
    if not request.user.is_superuser:
        messages.error(request, "Sorry, you don't have permission to do that.")
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        product_form = ProductForm(request.POST, request.FILES,
                                   instance=product)
        if product_form.is_valid():
            product_form.save()
            messages.success(request,
                             (f'You sucessfully edited {product.name}!'))
            return redirect(reverse('product_info', args=[product.id]))
        else:
            messages.error(request,
                           (f"I'm sorry, you were unable to edit {product.name}. \
                            Please check your form and try again."))
    else:
        product_form = ProductForm(instance=product)
        messages.info(request, f'You are editing the product {product.name}.')

    template = 'products/edit_product.html'
    context = {
        'product_form': product_form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """
    Remove the the product from the store
    """
    if not request.user.is_superuser:
        messages.error(request, "Sorry, you don't have permission to do that.")
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, f'You deleted {product.name} from the store.')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}
- Product Management - Add A Product
{% endblock %}

{% block content %}
<div class="overlay"></div>

<div class="container mb-4">
    <div class="row">
        <div class="col">
            <h1 class="mt-5 mb-3 text-navy text-center">Product Management</h1>
            <h5 class="text-muted text-center mb-4">Add A Product</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3 open-sans-text">
            <form method="POST" action="{% url 'add_product' %}" class="form mb-3" enctype="multipart/form-data">
                {% csrf_token %}
                {{ product_form | crispy }}
                <div class="text-right mt-4">
                    <a href="{% url 'home' %}" class="btn btn-custom rounded-0 mb-5">Cancel</a>
                    <button class="btn btn-custom rounded-0 mb-5" type="submit">Submit</button>
                </div>
            </form>
        </div>

    </div>
</div>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}
- Product Management - Edit A Product
{% endblock %}

{% block content %}
<div class="overlay"></div>

<div class="container mb-4">
    <div class="row">
        <div class="col">
            <h1 class="mt-5 mb-3 text-navy text-center">Product Management</h1>
            <h5 class="text-muted text-center mb-4">Edit A Product</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3 open-sans-text">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-3" enctype="multipart/form-data">
                {% csrf_token %}
                {{ product_form | crispy }}
                <div class="text-right mt-4">
                    <a href="{% url 'home' %}" class="btn btn-custom rounded-0 mb-5">Cancel</a>
                    <button class="btn btn-custom rounded-0 mb-5" type="submit">Edit A Product</button>
                </div>
            </form>
        </div>

    </div>
</div>
{% endblock %}

products/templates/products/product_info.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_title %}
- {{ product.name }}
{% endblock %}

{% block header %}
<div class="container header-container">
    <div class="row">
        <div class="col">

        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <!-- Product Image -->
            {% if product.image %}
            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="card-img-top img-fluid mt-3 mb-md-5">
            {% else %}
            <img src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}" class="card-img-top img-fluid mt-3 mb-md-5">
            {% endif %}
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <!-- Product info -->
            <div class="product-info-container mt-5 mb-5 mt-md-5">
                <h4 class="mb-0 font-weight-bold">{{ product.name }}</h4>

                {% if request.user.is_authenticated %}
                {% if request.user.is_superuser %}
                <a class="update-link text-primary open-sans-text"
                    href="{% url 'edit_product' product.id %}"><small>Update</small></a>
                <a class="remove-item text-danger open-sans-text mx-4"
                    href="{% url 'delete_product' product.id %}"><small>Remove</small></a>
                {% endif %}
                {% endif %}

                <p class="lead mb-0 text-left font-weight-bold">€{{ product.price }}</p>
                {% if product.category %}
                <p class="small mt-1 mb-0">
                    <a href="{% url 'products' %}?category={{ product.category.name }}" class="text-muted">
                        <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                    </a>
                </p>
                {% endif %}

                {% if product.rating %}
                <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                {% else %}
                <small class="text-muted">No Rating</small>
                {% endif %}
                <p class="mt-3">{{ product.description }}</p>
                <!-- Add to bag -->
                <form class="form" action="{% url 'add_to_shopping_bag' product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        {% with product.sizes_available as s %}
                        {% if s %}
                        <div class="col-12">
                            <p><strong>Size:</strong></p>
                            <select class="form-control rounded-0 w-50 open-sans-text" name="product_size"
                                id="id_product_size">
                                <option value="xs">XS</option>
                                <option value="s">S</option>
                                <option value="m" selected>M</option>
                                <option value="l">L</option>
                                <option value="xl">XL</option>
                                <option value="xxl">XXL</option>
                                <option value="xxxl">XXXL</option>
                            </select>
                        </div>
                        {% endif %}

                        <div class="col-12">
                            <p class="mt-3"><strong>Quantity:</strong></p>
                            <div class="form-group w-50">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button class="decrement-qty btn btn-custom rounded-0"
                                            data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}"
                                            aria-label="This button decreases the quantity of the item you wish to purchase">
                                            <span class="icon">
                                                <i class="fas fa-minus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    <input class="form-control qty_input" type="number" name="quantity" value="1"
                                        min="1" max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}"
                                        aria-label="This field allows you to specify the quantity of this item you wish to purchase">
                                    <div class="input-group-append">
                                        <button class="increment-qty btn btn-custom rounded-0"
                                            data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}"
                                            aria-label="This button increases the quantity of the item you wish to purchase">
                                            <span class="icon">
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col{% if s %}-12 mt-2{% endif %}">
                            <input type="submit" class="btn btn-custom rounded-0 text-uppercase mt-5"
                                value="Add to Bag">
                            <a href="{% url 'products' %}" class="btn  btn-custom rounded-0 mt-5">
                                <span class="icon">
                                    <i class="fas fa-circle-chevron-left"></i>
                                </span>
                                <span class="text-uppercase">Keep Shopping</span>
                            </a>
                        </div>
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        {% endwith %}
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% with product.sizes_available as s %}
    {% if s %}
    <div class="row float-left text-navy mb-4">
        <div class="col-sm-12 col-md-7">
            <div class="table-responsive rounded">
                <h4>Sizing Guide</h4>
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th class="col-2">Size</th>
                            <th class="col-4">Breed Example</th>
                            <th class="col-2">Back (cm)</th>
                            <th class="col-2">Chest (cm)</th>
                            <th class="col-2">Neck (cm)</th>
                        </tr>
                    </thead>
                    <tr class="open-sans-text">
                        <td class="text-bold">XS</td>
                        <td>Puppies and Kittens</td>
                        <td>20</td>
                        <td>26-30</td>
                        <td>16-19</td>
                    </tr>
                    <tr class="open-sans-text">
                        <td class="text-bold">S</td>
                        <td>Chihuahuas and Munchkin Cats</td>
                        <td>23</td>
                        <td>30-35</td>
                        <td>19-22</td>
                    </tr>
                    <tr class="open-sans-text">
                        <td class="text-bold">M</td>
                        <td>Small Maltese and Sphinx</td>
                        <td>30</td>
                        <td>35-40</td>
                        <td>22-26</td>
                    </tr>
                    <tr class="open-sans-text">
                        <td class="text-bold">L</td>
                        <td>Corgi and Maine Coon</td>
                        <td>33</td>
                        <td>40-46</td>
                        <td>26-30</td>
                    </tr>
                    <tr class="open-sans-text">
                        <td class="text-bold">XL</td>
                        <td>Cocker Spaniel and Savannah Cats</td>
                        <td>40</td>
                        <td>46-52</td>
                        <td>33-38</td>
                    </tr>
                    <tr class="open-sans-text">
                        <td class="text-bold">XXL</td>
                        <td>Small Collie and Staffys</td>
                        <td>45</td>
                        <td>52-60</td>
                        <td>36-41</td>
                    </tr>
                    <tr class="open-sans-text">
                        <td class="text-bold">XXXL</td>
                        <td>Labradors and German Shepherds</td>
                        <td>50</td>
                        <td>60-70</td>
                        <td>39-44</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-sm-12 col-md-5 align-self-center">
            <img src="{% static 'media/site-images/measure.png' %}" class="w-100"
                alt="How to measure your pet - The back is shown measured from the base of the neck to the base of the tail, the chest is measured around the widest part of the ribcage and the neck is measured around the neck where a collar would sit">
        </div>
    </div>
    {% endif %}
    {% endwith %}
</div>

<div class="container text-navy mb-5 mt-5">
    <div class="row">
        <div class="col-12 col-md-6">
            <h3 class="mb-5 text-center">View Comments</h3>
            {% if not product.comments.all %}
            <div class="comment">
                <p>No comments yet... Will you be the first to comment?</p>
            </div>
            {% else %}
            {% for comment in product.comments.all %}
            <div class="comment mb-5">
                <p><strong>{{ comment.title }}</strong></p>
                <p>{{ comment.body }}</p>
                <small class="text-muted">Comment by {{ comment.author|title }} on {{ comment.date_created }}</small>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="col-12 col-md-6 text-center">
            <h3 class="mb-5">Add A Comment</h3>
            {% if request.user.is_authenticated %}
            <form action="." method="POST" class="text-left">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Add Comment" class="btn btn-custom">
            </form>
            {% else %}
            <p>I'm sorry, you must be logged in to leave a comment. Please log in here.</p>
            <a href="{% url 'account_login' %}" class="btn btn-custom rounded-0">
                <span class="font-weight-bold">Log In</span>
            </a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}